### ISSUE TITLE
Issues trying to reproduce results

### ISSUE THREAD

**Issue by RdlP** [krasserm/super-resolution#33] opened 2019-11-05 11:52 UTC
Hello,

I am trying to run the sran notebook only for evaluation and I get the error shown below. I think that the error is that `images = [lr, pre_sr, gan_sr]` computed from
```
pre_sr = resolve_single(pre_generator, lr)
gan_sr = resolve_single(gan_generator, lr)
```
return Tensor datatype instead of numpy array and imshow function expect a numpy array. In that case, in the sran notebook I don't understand why the output from `resulve_single` function is not converted to numpy array and more important why it is working in the notebook shown in the github.

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-5-3b3a6990866c> in <module>
> ----> 1 resolve_and_plot('demo/0869x4-crop.png')
> 
> <ipython-input-4-27a4821c583c> in resolve_and_plot(lr_image_path)
>      16     for i, (img, title, pos) in enumerate(zip(images, titles, positions)):
>      17         plt.subplot(2, 2, pos)
> ---> 18         plt.imshow(img)
>      19         plt.title(title)
>      20         plt.xticks([])
> 
> ~/anaconda2/envs/keras/lib/python3.6/site-packages/matplotlib/pyplot.py in imshow(X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, shape, filternorm, filterrad, imlim, resample, url, data, **kwargs)
>    2699         filternorm=filternorm, filterrad=filterrad, imlim=imlim,
>    2700         resample=resample, url=url, **({"data": data} if data is not
> -> 2701         None else {}), **kwargs)
>    2702     sci(__ret)
>    2703     return __ret
> 
> ~/anaconda2/envs/keras/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
>    1808                         "the Matplotlib list!)" % (label_namer, func.__name__),
>    1809                         RuntimeWarning, stacklevel=2)
> -> 1810             return func(ax, *args, **kwargs)
>    1811 
>    1812         inner.__doc__ = _add_data_doc(inner.__doc__,
> 
> ~/anaconda2/envs/keras/lib/python3.6/site-packages/matplotlib/axes/_axes.py in imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, shape, filternorm, filterrad, imlim, resample, url, **kwargs)
>    5492                               resample=resample, **kwargs)
>    5493 
> -> 5494         im.set_data(X)
>    5495         im.set_alpha(alpha)
>    5496         if im.get_clip_path() is None:
> 
> ~/anaconda2/envs/keras/lib/python3.6/site-packages/matplotlib/image.py in set_data(self, A)
>     640         if (self._A.dtype != np.uint8 and
>     641                 not np.can_cast(self._A.dtype, float, "same_kind")):
> --> 642             raise TypeError("Image data cannot be converted to float")
>     643 
>     644         if not (self._A.ndim == 2
> 
> TypeError: Image data cannot be converted to float

**Comment by krasserm** [comment] 2019-11-05 12:21
Can you please share the environment details you're running the notebook in (i.e. version of packages, ...)?

**Comment by RdlP** [comment] 2019-11-05 14:38
I used environment.yml to create the conda env. The output from the installation is the following:

> expat-2.2.5-he 100% |################################| Time: 0:00:00   5.02 MB/s
> jpeg-9c-h14c39 100% |################################| Time: 0:00:00  13.12 MB/s
> libllvm9-9.0.0 100% |################################| Time: 0:00:00  63.50 MB/s
> libuuid-2.32.1 100% |################################| Time: 0:00:00  53.21 MB/s
> libxkbcommon-0 100% |################################| Time: 0:00:00  57.43 MB/s
> lz4-c-1.8.3-he 100% |################################| Time: 0:00:00  35.83 MB/s
> ncurses-6.1-hf 100% |################################| Time: 0:00:00   5.90 MB/s
> nspr-4.23-he1b 100% |################################| Time: 0:00:00  39.96 MB/s
> openssl-1.1.1c 100% |################################| Time: 0:00:00  46.78 MB/s
> pcre-8.43-he1b 100% |################################| Time: 0:00:00  45.89 MB/s
> pthread-stubs- 100% |################################| Time: 0:00:00   6.77 MB/s
> xorg-libxau-1. 100% |################################| Time: 0:00:00  14.39 MB/s
> xorg-libxdmcp- 100% |################################| Time: 0:00:00  14.03 MB/s
> gettext-0.19.8 100% |################################| Time: 0:00:00  48.00 MB/s
> libclang-9.0.0 100% |################################| Time: 0:00:00  63.30 MB/s
> libxcb-1.13-h1 100% |################################| Time: 0:00:00  46.63 MB/s
> libxml2-2.9.10 100% |################################| Time: 0:00:00  35.39 MB/s
> readline-8.0-h 100% |################################| Time: 0:00:00  35.78 MB/s
> tk-8.6.9-hed69 100% |################################| Time: 0:00:00  39.07 MB/s
> zstd-1.4.3-h3b 100% |################################| Time: 0:00:00  32.03 MB/s
> freetype-2.10. 100% |################################| Time: 0:00:00  32.33 MB/s
> glib-2.58.3-h6 100% |################################| Time: 0:00:00  39.86 MB/s
> libtiff-4.1.0- 100% |################################| Time: 0:00:00  31.30 MB/s
> sqlite-3.30.1- 100% |################################| Time: 0:00:00  35.00 MB/s
> dbus-1.13.6-he 100% |################################| Time: 0:00:00  33.78 MB/s
> fontconfig-2.1 100% |################################| Time: 0:00:00  30.96 MB/s
> gstreamer-1.14 100% |################################| Time: 0:00:00  40.21 MB/s
> nss-3.47-he751 100% |################################| Time: 0:00:00  35.69 MB/s
> python-3.6.7-h 100% |################################| Time: 0:00:00  63.18 MB/s
> certifi-2019.9 100% |################################| Time: 0:00:00  49.34 MB/s
> gst-plugins-ba 100% |################################| Time: 0:00:00  50.68 MB/s
> kiwisolver-1.1 100% |################################| Time: 0:00:00  52.05 MB/s
> numpy-1.17.3-p 100% |################################| Time: 0:00:00  47.38 MB/s
> six-1.12.0-py3 100% |################################| Time: 0:00:00  33.02 MB/s
> tornado-6.0.3- 100% |################################| Time: 0:00:00  41.91 MB/s
> tqdm-4.32.1-py 100% |################################| Time: 0:00:00  24.05 MB/s
> pillow-6.0.0-p 100% |################################| Time: 0:00:01 443.30 kB/s
> python-dateuti 100% |################################| Time: 0:00:00  32.33 MB/s
> qt-5.12.5-hd8c 100% |################################| Time: 0:00:01  69.76 MB/s
> setuptools-41. 100% |################################| Time: 0:00:00  49.24 MB/s
> matplotlib-bas 100% |################################| Time: 0:00:00  45.54 MB/s
> pyqt-5.12.3-py 100% |################################| Time: 0:00:00  60.54 MB/s
> wheel-0.33.6-p 100% |################################| Time: 0:00:00  45.41 MB/s
> matplotlib-3.1 100% |################################| Time: 0:00:00  12.65 MB/s
> pip-19.3.1-py3 100% |################################| Time: 0:00:00  39.08 MB/s
> Collecting tensorflow-gpu==2.0.0
>   Downloading https://files.pythonhosted.org/packages/25/44/47f0722aea081697143fbcf5d2aa60d1aee4aaacb5869aee2b568974777b/tensorflow_gpu-2.0.0-cp36-cp36m-manylinux2010_x86_64.whl (380.8MB)
>      |████████████████████████████████| 380.8MB 76kB/s 
> Collecting tensorflow-addons==0.5.2
>   Downloading https://files.pythonhosted.org/packages/03/b6/574034405ad527eec40ac426081694f50da9766db6b81c2b899041c44ef2/tensorflow_addons-0.5.2-cp36-cp36m-manylinux2010_x86_64.whl (1.6MB)
>      |████████████████████████████████| 1.6MB 17.9MB/s 
> Collecting google-pasta>=0.1.6
>   Downloading https://files.pythonhosted.org/packages/c3/fd/1e86bc4837cc9a3a5faf3db9b1854aa04ad35b5f381f9648fbe81a6f94e4/google_pasta-0.1.8-py3-none-any.whl (57kB)
>      |████████████████████████████████| 61kB 1.2MB/s 
> Collecting keras-preprocessing>=1.0.5
>   Downloading https://files.pythonhosted.org/packages/28/6a/8c1f62c37212d9fc441a7e26736df51ce6f0e38455816445471f10da4f0a/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl (41kB)
>      |████████████████████████████████| 51kB 3.7MB/s 
> Requirement already satisfied: six>=1.10.0 in /home/angelluis/anaconda2/envs/sisr/lib/python3.6/site-packages (from tensorflow-gpu==2.0.0) (1.12.0)
> Collecting grpcio>=1.8.6
>   Downloading https://files.pythonhosted.org/packages/30/54/c9810421e41ec0bca2228c6f06b1b1189b196b69533cbcac9f71b44727f8/grpcio-1.24.3-cp36-cp36m-manylinux2010_x86_64.whl (2.2MB)
>      |████████████████████████████████| 2.2MB 2.6MB/s 
> Collecting gast==0.2.2
>   Downloading https://files.pythonhosted.org/packages/4e/35/11749bf99b2d4e3cceb4d55ca22590b0d7c2c62b9de38ac4a4a7f4687421/gast-0.2.2.tar.gz
> Collecting astor>=0.6.0
>   Downloading https://files.pythonhosted.org/packages/d1/4f/950dfae467b384fc96bc6469de25d832534f6b4441033c39f914efd13418/astor-0.8.0-py2.py3-none-any.whl
> Collecting termcolor>=1.1.0
>   Downloading https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
> Collecting wrapt>=1.11.1
>   Downloading https://files.pythonhosted.org/packages/23/84/323c2415280bc4fc880ac5050dddfb3c8062c2552b34c2e512eb4aa68f79/wrapt-1.11.2.tar.gz
> Requirement already satisfied: numpy<2.0,>=1.16.0 in /home/angelluis/anaconda2/envs/sisr/lib/python3.6/site-packages (from tensorflow-gpu==2.0.0) (1.17.3)
> Collecting tensorflow-estimator<2.1.0,>=2.0.0
>   Downloading https://files.pythonhosted.org/packages/fc/08/8b927337b7019c374719145d1dceba21a8bb909b93b1ad6f8fb7d22c1ca1/tensorflow_estimator-2.0.1-py2.py3-none-any.whl (449kB)
>      |████████████████████████████████| 450kB 25.6MB/s 
> Collecting absl-py>=0.7.0
>   Downloading https://files.pythonhosted.org/packages/3b/72/e6e483e2db953c11efa44ee21c5fdb6505c4dffa447b4263ca8af6676b62/absl-py-0.8.1.tar.gz (103kB)
>      |████████████████████████████████| 112kB 27.1MB/s 
> Collecting keras-applications>=1.0.8
>   Downloading https://files.pythonhosted.org/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl (50kB)
>      |████████████████████████████████| 51kB 3.1MB/s 
> Collecting tensorboard<2.1.0,>=2.0.0
>   Downloading https://files.pythonhosted.org/packages/d3/9e/a48cd34dd7b672ffc227b566f7d16d63c62c58b542d54efa45848c395dd4/tensorboard-2.0.1-py3-none-any.whl (3.8MB)
>      |████████████████████████████████| 3.8MB 26.4MB/s 
> Collecting protobuf>=3.6.1
>   Downloading https://files.pythonhosted.org/packages/a8/52/d8d2dbff74b8bf517c42db8d44c3f9ef6555e6f5d6caddfa3f207b9143df/protobuf-3.10.0-cp36-cp36m-manylinux1_x86_64.whl (1.3MB)
>      |████████████████████████████████| 1.3MB 27.6MB/s 
> Requirement already satisfied: wheel>=0.26 in /home/angelluis/anaconda2/envs/sisr/lib/python3.6/site-packages (from tensorflow-gpu==2.0.0) (0.33.6)
> Collecting opt-einsum>=2.3.2
>   Downloading https://files.pythonhosted.org/packages/b8/83/755bd5324777875e9dff19c2e59daec837d0378c09196634524a3d7269ac/opt_einsum-3.1.0.tar.gz (69kB)
>      |████████████████████████████████| 71kB 4.4MB/s 
> Collecting h5py
>   Downloading https://files.pythonhosted.org/packages/60/06/cafdd44889200e5438b897388f3075b52a8ef01f28a17366d91de0fa2d05/h5py-2.10.0-cp36-cp36m-manylinux1_x86_64.whl (2.9MB)
>      |████████████████████████████████| 2.9MB 25.6MB/s 
> Collecting markdown>=2.6.8
>   Downloading https://files.pythonhosted.org/packages/c0/4e/fd492e91abdc2d2fcb70ef453064d980688762079397f779758e055f6575/Markdown-3.1.1-py2.py3-none-any.whl (87kB)
>      |████████████████████████████████| 92kB 5.1MB/s 
> Requirement already satisfied: setuptools>=41.0.0 in /home/angelluis/anaconda2/envs/sisr/lib/python3.6/site-packages (from tensorboard<2.1.0,>=2.0.0->tensorflow-gpu==2.0.0) (41.6.0.post20191101)
> Collecting google-auth-oauthlib<0.5,>=0.4.1
>   Downloading https://files.pythonhosted.org/packages/7b/b8/88def36e74bee9fce511c9519571f4e485e890093ab7442284f4ffaef60b/google_auth_oauthlib-0.4.1-py2.py3-none-any.whl
> Collecting google-auth<2,>=1.6.3
>   Downloading https://files.pythonhosted.org/packages/2f/81/d1e7d9974ba7c886f6d133a8baae18cb8d92b2d09bcc4f46328306825de0/google_auth-1.7.0-py2.py3-none-any.whl (74kB)
>      |████████████████████████████████| 81kB 5.1MB/s 
> Collecting werkzeug>=0.11.15
>   Downloading https://files.pythonhosted.org/packages/ce/42/3aeda98f96e85fd26180534d36570e4d18108d62ae36f87694b476b83d6f/Werkzeug-0.16.0-py2.py3-none-any.whl (327kB)
>      |████████████████████████████████| 327kB 29.1MB/s 
> Collecting requests-oauthlib>=0.7.0
>   Downloading https://files.pythonhosted.org/packages/c2/e2/9fd03d55ffb70fe51f587f20bcf407a6927eb121de86928b34d162f0b1ac/requests_oauthlib-1.2.0-py2.py3-none-any.whl
> Collecting rsa<4.1,>=3.1.4
>   Downloading https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
> Collecting pyasn1-modules>=0.2.1
>   Downloading https://files.pythonhosted.org/packages/52/50/bb4cefca37da63a0c52218ba2cb1b1c36110d84dcbae8aa48cd67c5e95c2/pyasn1_modules-0.2.7-py2.py3-none-any.whl (131kB)
>      |████████████████████████████████| 133kB 26.1MB/s 
> Collecting cachetools<3.2,>=2.0.0
>   Downloading https://files.pythonhosted.org/packages/2f/a6/30b0a0bef12283e83e58c1d6e7b5aabc7acfc4110df81a4471655d33e704/cachetools-3.1.1-py2.py3-none-any.whl
> Collecting requests>=2.0.0
>   Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
>      |████████████████████████████████| 61kB 4.5MB/s 
> Collecting oauthlib>=3.0.0
>   Downloading https://files.pythonhosted.org/packages/05/57/ce2e7a8fa7c0afb54a0581b14a65b56e62b5759dbc98e80627142b8a3704/oauthlib-3.1.0-py2.py3-none-any.whl (147kB)
>      |████████████████████████████████| 153kB 28.0MB/s 
> Collecting pyasn1>=0.1.3
>   Downloading https://files.pythonhosted.org/packages/a1/71/8f0d444e3a74e5640a3d5d967c1c6b015da9c655f35b2d308a55d907a517/pyasn1-0.4.7-py2.py3-none-any.whl (76kB)
>      |████████████████████████████████| 81kB 5.2MB/s 
> Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
>   Downloading https://files.pythonhosted.org/packages/e0/da/55f51ea951e1b7c63a579c09dd7db825bb730ec1fe9c0180fc77bfb31448/urllib3-1.25.6-py2.py3-none-any.whl (125kB)
>      |████████████████████████████████| 133kB 27.0MB/s 
> Collecting chardet<3.1.0,>=3.0.2
>   Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
>      |████████████████████████████████| 143kB 26.7MB/s 
> Collecting idna<2.9,>=2.5
>   Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
>      |████████████████████████████████| 61kB 4.6MB/s 
> Requirement already satisfied: certifi>=2017.4.17 in /home/angelluis/anaconda2/envs/sisr/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.1.0,>=2.0.0->tensorflow-gpu==2.0.0) (2019.9.11)
> Building wheels for collected packages: gast, termcolor, wrapt, absl-py, opt-einsum
>   Building wheel for gast (setup.py) ... done
>   Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7540 sha256=997103d730f00bfebbff00c30c9620fd900db3e76d3804ed7399c115b3aaaf9d
>   Stored in directory: /home/angelluis/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
>   Building wheel for termcolor (setup.py) ... done
>   Created wheel for termcolor: filename=termcolor-1.1.0-cp36-none-any.whl size=4832 sha256=5410c8b4e50e24645319d60faa3f00e238567d30477394d134d656d999f3994c
>   Stored in directory: /home/angelluis/.cache/pip/wheels/7c/06/54/bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6
>   Building wheel for wrapt (setup.py) ... done
>   Created wheel for wrapt: filename=wrapt-1.11.2-cp36-cp36m-linux_x86_64.whl size=66194 sha256=a48d22dae6982f6568bb22d94b611c1d2b4296f5fa16fbcf9e16d952c346fa46
>   Stored in directory: /home/angelluis/.cache/pip/wheels/d7/de/2e/efa132238792efb6459a96e85916ef8597fcb3d2ae51590dfd
>   Building wheel for absl-py (setup.py) ... done
>   Created wheel for absl-py: filename=absl_py-0.8.1-cp36-none-any.whl size=121167 sha256=f2cf32251f917ca7ab74b54e48d3e543809a1b6b3570b4038d3ac8ef1b358076
>   Stored in directory: /home/angelluis/.cache/pip/wheels/a7/15/a0/0a0561549ad11cdc1bc8fa1191a353efd30facf6bfb507aefc
>   Building wheel for opt-einsum (setup.py) ... done
>   Created wheel for opt-einsum: filename=opt_einsum-3.1.0-cp36-none-any.whl size=61682 sha256=caed6d65794064043b9eecf68f10c42cdcd3e7860c51a257a8e77edb457544e4
>   Stored in directory: /home/angelluis/.cache/pip/wheels/2c/b1/94/43d03e130b929aae7ba3f8d15cbd7bc0d1cb5bb38a5c721833
> Successfully built gast termcolor wrapt absl-py opt-einsum
> Installing collected packages: google-pasta, keras-preprocessing, grpcio, gast, astor, termcolor, wrapt, tensorflow-estimator, absl-py, h5py, keras-applications, markdown, pyasn1, rsa, pyasn1-modules, cachetools, google-auth, urllib3, chardet, idna, requests, oauthlib, requests-oauthlib, google-auth-oauthlib, protobuf, werkzeug, tensorboard, opt-einsum, tensorflow-gpu, tensorflow-addons
> Successfully installed absl-py-0.8.1 astor-0.8.0 cachetools-3.1.1 chardet-3.0.4 gast-0.2.2 google-auth-1.7.0 google-auth-oauthlib-0.4.1 google-pasta-0.1.8 grpcio-1.24.3 h5py-2.10.0 idna-2.8 keras-applications-1.0.8 keras-preprocessing-1.1.0 markdown-3.1.1 oauthlib-3.1.0 opt-einsum-3.1.0 protobuf-3.10.0 pyasn1-0.4.7 pyasn1-modules-0.2.7 requests-2.22.0 requests-oauthlib-1.2.0 rsa-4.0 tensorboard-2.0.1 tensorflow-addons-0.5.2 tensorflow-estimator-2.0.1 tensorflow-gpu-2.0.0 termcolor-1.1.0 urllib3-1.25.6 werkzeug-0.16.0 wrapt-1.11.2
> #
> # To activate this environment, use:
> # > source activate sisr
> #
> # To deactivate an active environment, use:
> # > source deactivate
> #

**Comment by krasserm** [comment] 2019-11-05 16:47
I'm unable to reproduce the issue. I cloned the repo, did setup the environment as described, ran `example-srgan.ipynb` (demo only) and it works as expected. Are there any changes you've made to the sources/notebook?

**Comment by krasserm** [comment] 2019-11-07 15:21
Closing this for now. Please re-open if you can provide sample code for reproducing.

**Closed by krasserm** 2019-11-07 15:21 UTC

**Comment by akkara** [comment] 2020-09-26 18:31
The code below throws "TypeError: Image data of dtype object cannot be converted to float" Plt cant show SR data as image. How to solve this?

```
from model import resolve_single
from model.edsr import edsr

from utils import load_image, plot_sample

from matplotlib import pyplot as plt

model = edsr(scale=4, num_res_blocks=16)
model.load_weights('weights/article/weights-edsr-16-x4-fine-tuned.h5')

lr = load_image('demo/0851x4-crop.png')
sr = resolve_single(model, lr)

plot_sample(lr, sr)
```
