### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by Kavit212** [krasserm/super-resolution#62] opened 2020-08-25 11:04 UTC
Hi, thanks for making your great work available to everyone. 
Is it possible to train the model with my own custom dataset ?
I am planning to train the model on microscopy images.
Could you kindly give me some clues on which lines of codes need to be changed to make this possible? 

Thank you very much

**Comment by krasserm** [comment] 2020-08-26 04:53
This is a duplicate of #8. Also read #19 for details regarding the creation of downgraded images in your own training set.

**Closed by krasserm** 2020-08-26 04:53 UTC
