### ISSUE TITLE
Saving output file (sr) 

### ISSUE THREAD

**Issue by SidV256** [krasserm/super-resolution#78] opened 2021-02-26 19:58 UTC
I am new in coding and as such I was able to execute the code and plot the results on one of my images (lr vs sr) but I have used multiple methods to save the output file but nothing worked

**Comment by krasserm** [comment] 2021-02-27 05:51
That's probably a duplicate of #65. Please follow the link for details.

**Closed by krasserm** 2021-02-27 05:51 UTC
